### ISSUE TITLE
O que deve ser feito

### ISSUE THREAD

**Issue by VitorBSP** [VitorBSP/Tempo_Tela#1]
- [x] Introdução
- [x] Descrição das variáveis
- [x] Análise Descritiva
- [x] Testes: KMO, Alfa de Cronbach e Barttlet
- [x] Testes de associação e razão de chances (?)

Gráficos:

- [x] Dias da Semana: Só Graficos
- [x] Tabelas de frequência com: Curso, Semestre, Aplicativo para tempo
- [x] Tabelas cruzadas com: Sexo, Ocupação, Plataforma de estudo, Dispositivos, Média-Antes Pandemia, Média-Depois Pandemia, Streaming, Rede Social
- [x] Ultimas variáveis testar influência: Sexo, Idade, Ocupação, Plataforma de Estudo, Média-Antes Pandemia, Média-Depois Pandemia

**Comment by AlissonRP** [comment]
### Tabelas de frequência
- [x] Curso
- [x] Semestre
- [x] Aplicativo para tempo 

### Tabelas 2x2

- [x] Sexo x Dispositivos  
- [x] Ocupação x Dispositivos  
- [x]  Ocupação x Rede social
- [x]  Ocupação x Streaming
- [x] Sexo x Curso
- [x] Dispositivos usados x  e plataforma de estudo
- [x] Média antes x Média depois


### Gráficos
- [x] Dias da semana

**Comment by VitorBSP** [comment]
### Tabelas de frequência
- [x] Metas
- [x] Criatividade
- [x] Novas ferramentas
- [x] Rendimento
- [x] Concentração

### Tabelas 2x2

- [x]  Sexo x Ocupação
- [x]  Ocupação x Video Games 
- [x]  Ocupação x Idade
- [x]  Idade x Rede Social
- [x]  Médias depois x Metas
- [x]  Ocupação x Metas
- [x]  Plataforma de Estudo x Metas
- [x]  Médias depois x Criatividade
- [x]  Sexo x Criatividade
- [x]  Médias depois x Novas ferramentas
- [x]  Plataforma de Estudo x Novas ferramentas
- [x]  Médias depois x Trabalho em equipe
- [x]  Sexo x Trabalho em equipe
- [x]  Médias depois x Concentração
- [x]  Plataforma de Estudo x Concentração
- [x]  Sexo x Concentração

### Gráficos
- [x] Ferramenta
- [x] Metas
- [x] Criatividade
- [x] Novas ferramentas
- [x] Trabalho em equipe
- [x] Rendimento
- [x] Concentração
